In [1]:
import numpy as np

In [2]:
np

<module 'numpy' from '/home/codespace/.local/lib/python3.12/site-packages/numpy/__init__.py'>

## Creating arrays

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [5]:
np.full(10, 3.5)

array([3.5, 3.5, 3.5, 3.5, 3.5, 3.5, 3.5, 3.5, 3.5, 3.5])

In [8]:
a = np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [10]:
a[2] = 10

In [11]:
a

array([ 1,  2, 10,  4,  5,  6])

In [12]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [14]:
np.linspace(0,1,11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

## Multi-dimensional arrays

In [15]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [17]:
n = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]])

In [18]:
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
n[1,1]

np.int64(5)

In [20]:
n[1,1]=100

In [21]:
n

array([[  1,   2,   3],
       [  4, 100,   6],
       [  7,   8,   9]])

In [22]:
n[2]

array([7, 8, 9])

In [23]:
n[2]=[1,1,1]
n

array([[  1,   2,   3],
       [  4, 100,   6],
       [  1,   1,   1]])

In [26]:
n[2] = np.array([1,2,3])

In [27]:
n

array([[  1,   2,   3],
       [  4, 100,   6],
       [  1,   2,   3]])

In [28]:
n[:,2]

array([3, 6, 3])

## Randomly generated arrays

In [34]:
np.random.seed(2)
np.random.rand(5,2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [35]:
np.random.seed(2)
np.random.randn(5,2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [36]:
np.random.seed(2)
np.random.randint(low=0,high=100,size=(5,2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

## Element wise operations

In [37]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [38]:
a + 1

array([1, 2, 3, 4, 5])

In [39]:
a * 2

array([0, 2, 4, 6, 8])

In [40]:
a/100

array([0.  , 0.01, 0.02, 0.03, 0.04])

In [43]:
b = (10 + (a*2)) ** 2

In [44]:
a + b

array([100, 145, 198, 259, 328])

In [45]:
a - b

array([-100, -143, -194, -253, -320])

In [46]:
a/b

array([0.        , 0.00694444, 0.01020408, 0.01171875, 0.01234568])

In [47]:
a *b

array([   0,  144,  392,  768, 1296])

In [49]:
len(a)

5

In [50]:
len(b)

5

## Comparison operations

In [51]:
a >=2

array([False, False,  True,  True,  True])

In [52]:
a > b

array([False, False, False, False, False])

In [54]:
a[a < b]

array([0, 1, 2, 3, 4])

## Summarizing operations

In [55]:
a.min()

np.int64(0)

In [56]:
a.max()

np.int64(4)

In [57]:
a.sum()

np.int64(10)

In [58]:
a.mean()

np.float64(2.0)

In [59]:
a.std()

np.float64(1.4142135623730951)

In [60]:
n.sum()

np.int64(122)