In [1]:
import numpy as np

### Vector-vector multiplication

In [2]:
def vector_vector_multiplication(u,v):
    assert u.shape[0] == v.shape[0]

    n = u.shape[0]

    result = 0.0

    for i in range(n):
        result = result + u[i] * v[i]

    return result

In [5]:
np.random.seed(10)
u = np.random.randint(1,10,4)
u

array([5, 1, 2, 1])

In [6]:
np.random.seed(11)
v = np.random.randint(1,10,4)
v

array([1, 2, 8, 2])

In [7]:
vector_vector_multiplication(u,v)

np.float64(25.0)

### Matrix-vector multiplication

In [9]:
def matrix_vector_multiplication(U,v):
    assert U.shape[1] == v.shape[0]

    n = U.shape[0]

    result = np.zeros(n)

    for i in range(n):
        result[i] = vector_vector_multiplication(U[i], v)

    return result

In [14]:
U = np.array([[1,2,3,1],
              [4,5,6,3],
              [7,8,9,5]])

In [15]:
matrix_vector_multiplication(U, v)

array([ 31.,  68., 105.])

In [20]:
U.dot(v)

array([ 31,  68, 105])

### Matrix-matrix multiplication

In [16]:
def matrix_matrix_multiplication(U,V):
    assert U.shape[1] == V.shape[0]

    num_rows = U.shape[0]
    num_cols = V.shape[1]

    result = np.zeros((num_rows, num_cols))

    for i in range(num_cols):
        vi = V[:, i]
        Uvi = matrix_vector_multiplication(U, vi)
        result[:, i] = Uvi

    return result

In [17]:
V = np.array([[1,3,2],
              [2,4,5],
              [4,5,6],
              [6,7,4]])

In [18]:
matrix_matrix_multiplication(U,V)

array([[ 23.,  33.,  34.],
       [ 56.,  83.,  81.],
       [ 89., 133., 128.]])

In [19]:
U.dot(V)

array([[ 23,  33,  34],
       [ 56,  83,  81],
       [ 89, 133, 128]])

### Identity matrix

In [22]:
I = np.eye(4)

In [23]:
U.dot(I)

array([[1., 2., 3., 1.],
       [4., 5., 6., 3.],
       [7., 8., 9., 5.]])

### Inverse
Only square matrixes can be inversed

In [24]:
Vs = V[[0,1,2]]

In [25]:
Vs

array([[1, 3, 2],
       [2, 4, 5],
       [4, 5, 6]])

In [27]:
Vs_inv = np.linalg.inv(Vs)
Vs_inv

array([[-0.09090909, -0.72727273,  0.63636364],
       [ 0.72727273, -0.18181818, -0.09090909],
       [-0.54545455,  0.63636364, -0.18181818]])

In [28]:
Vs_inv.dot(Vs)

array([[1.00000000e+00, 1.11022302e-16, 2.22044605e-16],
       [0.00000000e+00, 1.00000000e+00, 5.55111512e-17],
       [1.11022302e-16, 3.33066907e-16, 1.00000000e+00]])